version: "3.8"

services:
  tour:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: tour
    volumes:
      - ./src:/var/www/tour
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=34.84.182.216
      - DB_PORT=3306
      - DB_DATABASE=skyhotel
      - DB_USERNAME=sky_system
      - DB_PASSWORD=2tI%9w.HaSV&Hq-g

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/tour
    restart: always
